export type PageSection = { heading: string; paragraphs: string[]; bullets?: string[] };
export type SitePage = { title: string; description: string; h1: string; intro: string; eyebrow: string; sections: PageSection[]; faq?: { q: string; a: string }[]; related: [string, string][]; kind?: "service" | "standard" | "policy" };

export const pages: Record<string, SitePage> = {
  about: { title: "About SolarNow | Solar Company Nagpur", description: "Learn how SolarNow Enterprises approaches solar system planning and installation for homes and businesses in Nagpur and Kalmeshwar.", h1: "Local solar planning, built on clear decisions.", intro: "SolarNow Enterprises helps property owners across Nagpur and Kalmeshwar assess, design and install solar systems with practical guidance at every stage.", eyebrow: "About SolarNow Enterprises", sections: [
    { heading: "A solar company focused on fit, not packages", paragraphs: ["A useful solar proposal begins with the property. Roof area, shade, structure, electrical connection, consumption pattern and future energy needs all affect the right design. We bring those factors together so customers can compare a system on its real merits.", "Our role is to make the technical choices understandable: why a capacity is suggested, how the system connects, what can affect generation and what upkeep it will need."] },
    { heading: "Serving Nagpur from Kalmeshwar", paragraphs: ["SolarNow Enterprises is based on Katol Nagpur Road in Kalmeshwar and serves residential, commercial and industrial customers across the wider Nagpur region. Local access supports site visits, installation coordination and ongoing service."], bullets: ["Residential rooftop solar", "Commercial and industrial solar", "On-grid, off-grid and hybrid systems", "Solar maintenance and system support"] },
    { heading: "What you can expect", paragraphs: ["We do not use invented awards, inflated generation promises or one-size-fits-all estimates. Customers receive a recommendation shaped by site observations, available information and the applicable electricity connection requirements."] }
  ], related: [["Explore solar solutions", "/solar-solutions"], ["View our process", "/rooftop-solar-nagpur"], ["Request a site survey", "/get-quote"]] },

  "residential-solar-nagpur": service("Residential Solar Installation in Nagpur", "Residential solar systems for Nagpur homes", "Plan a rooftop solar system around your home’s electricity use, roof and long-term goals. SolarNow serves Nagpur, Kalmeshwar and nearby areas.", "Home solar should reduce grid dependence without making daily life more complicated.", [
    ["Is residential solar right for your home?", "A home with usable, largely shade-free roof space and a meaningful electricity bill may be a good candidate. The strongest fit depends on daytime consumption, sanctioned load, roof condition and whether backup is required."],
    ["How a home solar system works", "Solar panels produce direct current electricity from daylight. An inverter converts it for household use. In an on-grid system, your home uses solar power first and exchanges eligible surplus with the grid through the applicable metering arrangement. Battery-based systems store energy for later use."],
    ["How the system size is selected", "We look at recent electricity bills, daytime load, available roof area, shading, panel orientation, connection type and future needs such as air-conditioning or an electric vehicle. A larger system is not automatically a better system."],
    ["Installation and care", "The process typically includes an initial discussion, site survey, engineering, equipment planning, mounting and electrical work, testing and handover. Panels benefit from periodic cleaning and visual checks; inverter alerts and generation trends should also be monitored."]
  ], [["Estimate system size", "/solar-calculator"], ["Read subsidy guidance", "/solar-subsidy"], ["Request a home survey", "/get-quote"]], [
    ["How much roof space does a home solar system need?", "It depends on panel dimensions, access paths, shade and layout. A site survey is needed before capacity can be confirmed."], ["Will solar work during a power cut?", "A standard on-grid inverter shuts down during an outage for grid safety. Backup requires a suitable hybrid or off-grid design."], ["Does every home qualify for subsidy?", "Eligibility depends on the current scheme, consumer category, approved process and equipment requirements. Check current official guidance before committing."]
  ]),
  "commercial-solar-nagpur": service("Commercial Solar Installation in Nagpur", "Commercial solar designed around business demand", "SolarNow plans commercial rooftop solar systems for offices, shops, institutions and business facilities across Nagpur.", "Businesses with steady daytime electricity use can often consume a high share of solar generation directly.", [
    ["Where commercial rooftop solar fits", "Commercial solar can suit offices, retail buildings, hospitals, schools, hotels, workshops and other sites with daytime load and suitable roof or open space. The design should reflect operating hours, tariff, demand profile and ownership of the premises."],
    ["Designing around the load curve", "Monthly bill totals alone do not show when electricity is used. We examine daytime demand, seasonal variation, sanctioned load, transformer and connection details, and roof constraints before suggesting capacity."],
    ["Evaluating the business case", "Savings depend on self-consumption, applicable tariff, generation, system cost, financing and policy. A credible proposal makes its assumptions visible and does not treat a best-case estimate as a guarantee."],
    ["Installation with operating continuity in mind", "Access, safety, cable routes, shutdown windows and future roof maintenance are considered during planning. The system should be documented so facilities teams can monitor it and arrange maintenance efficiently."]
  ], [["See project approach", "/solar-projects"], ["Use the solar calculator", "/solar-calculator"], ["Discuss a commercial site", "/contact"]]),
  "industrial-solar-nagpur": service("Industrial Solar Installation in Nagpur", "Solar power engineered for industrial sites", "Explore industrial rooftop solar for factories, warehouses and production facilities in Nagpur and surrounding industrial areas.", "Industrial solar requires careful electrical, structural and operational coordination—not only panel placement.", [
    ["A fit for energy-intensive facilities", "Factories and warehouses often have large roofs and consistent daytime loads. This can support strong self-consumption, but the final system must suit roof condition, process load, connection infrastructure and operational constraints."],
    ["Engineering considerations", "Industrial design reviews roof loading and corrosion conditions, walkways and fire access, earthing, lightning protection, cable routing, inverter placement and the point of interconnection. Electrical protection and documentation are central to safe delivery."],
    ["Capacity and generation planning", "Interval load data, shifts, shutdown periods and seasonal demand are useful inputs. We also account for usable roof geometry, shade from vents or equipment, soiling and the losses that separate nameplate capacity from real energy output."],
    ["Operations and maintenance", "Generation monitoring, planned cleaning, thermographic or electrical inspection where appropriate, torque checks and prompt attention to inverter faults help preserve performance. Maintenance access should be designed in from the start."]
  ], [["Explore maintenance", "/solar-maintenance"], ["Review projects", "/solar-projects"], ["Arrange a facility survey", "/get-quote"]]),
  "rooftop-solar-nagpur": service("Rooftop Solar Installation Nagpur", "Turn available roof area into useful energy", "Rooftop solar design and installation for homes, businesses and industrial properties across Nagpur and Kalmeshwar.", "A strong rooftop solar design balances energy goals with the realities of the roof beneath it.", [
    ["What a rooftop system includes", "A rooftop installation normally includes photovoltaic modules, a mounting structure, inverter, DC and AC protection, earthing, cables and monitoring. Grid-connected systems may also require metering and utility-side approvals under applicable rules."],
    ["The roof survey comes first", "We assess usable area, shade through the day, roof condition, drainage, parapets, access, orientation and nearby obstructions. Structural suitability must be considered before equipment is installed."],
    ["On-grid, off-grid or hybrid?", "On-grid systems are often used where the grid is available and energy savings are the main goal. Off-grid systems are designed around independent supply and storage. Hybrid systems combine solar, grid and batteries for selected backup needs."],
    ["From design to handover", "After survey and design, equipment and installation details are finalised. Mounting and electrical work are completed, protections tested and monitoring explained. Documentation and maintenance guidance support the system after commissioning."]
  ], [["Compare on-grid systems", "/on-grid-solar"], ["Residential rooftop solar", "/residential-solar-nagpur"], ["Commercial rooftop solar", "/commercial-solar-nagpur"]]),
  "on-grid-solar": service("On Grid Solar System Nagpur", "Use solar alongside the electricity grid", "Understand on-grid solar systems for homes and businesses in Nagpur, including self-consumption, metering and outage behaviour.", "An on-grid system is designed to reduce grid electricity use while remaining connected to the distribution network.", [
    ["How on-grid solar works", "Panels and an on-grid inverter supply electricity to the property when solar energy is available. Consumption is served locally first; eligible surplus and shortfall are handled through the grid according to the applicable metering arrangement."],
    ["Who it suits", "On-grid solar can suit properties with a reliable grid connection, usable roof space and a goal of lowering electricity purchases. It is commonly considered by homes, offices, shops and industrial facilities."],
    ["What happens in a power cut", "For safety, a standard grid-tied inverter stops exporting power when the grid is down. This anti-islanding behaviour protects line workers. Customers who need backup should assess a compatible hybrid or battery system."],
    ["Important design inputs", "Connection type, sanctioned load, energy use, export rules, inverter capacity, roof layout and protection equipment all influence design. Current distribution-company procedures should be confirmed for each project."]
  ], [["Compare hybrid solar", "/hybrid-solar"], ["Read subsidy guidance", "/solar-subsidy"], ["Request a survey", "/get-quote"]]),
  "off-grid-solar": service("Off Grid Solar System Nagpur", "Independent solar power with battery storage", "Explore off-grid solar systems in Nagpur for locations or loads that need electricity independent of the utility grid.", "Off-grid solar is an energy system built around the load, available sunlight and the autonomy required.", [
    ["How off-grid solar works", "Solar panels charge batteries through a suitable controller or inverter system. Stored energy supplies selected loads when solar production is low or unavailable. Some designs include generator support for extended low-generation periods."],
    ["When it makes sense", "Off-grid systems may suit remote sites, agricultural or security loads, telecom applications and places where grid extension is difficult. They can also serve a defined critical load rather than an entire property."],
    ["Sizing is driven by energy and autonomy", "Accurate appliance wattage, operating hours, surge loads, days of backup, battery depth of discharge and seasonal solar conditions are required. Underestimating load or storage needs causes poor reliability and shorter battery life."],
    ["Maintenance considerations", "Batteries require compatible operating temperatures, correct settings and periodic checks. Panels, terminals, protections and system performance should also be inspected on a planned schedule."]
  ], [["Compare hybrid systems", "/hybrid-solar"], ["Estimate your load", "/solar-calculator"], ["Discuss an off-grid need", "/contact"]]),
  "hybrid-solar": service("Hybrid Solar System Nagpur", "Solar savings with selected backup capability", "Hybrid solar systems combine solar, grid and battery storage for Nagpur properties that need both energy savings and backup.", "A hybrid system coordinates multiple energy sources, so load selection and control strategy matter as much as capacity.", [
    ["How a hybrid system works", "A compatible hybrid inverter manages power from solar panels, the grid and batteries. Depending on system settings, solar can supply loads, charge batteries and reduce grid use while stored energy supports selected circuits during an outage."],
    ["Choosing backup loads", "Trying to back up every appliance can make storage costly. Essential loads—such as lights, fans, connectivity, refrigeration or selected equipment—are identified first, including starting surges and required backup duration."],
    ["Battery and inverter design", "Battery chemistry, usable capacity, cycle life, warranty terms, operating temperature and replacement planning should be considered. The inverter must be compatible with the battery and the property’s electrical arrangement."],
    ["Is hybrid the right choice?", "Hybrid solar can be useful where outages affect comfort or operations, but it adds cost and complexity. Where the grid is stable and savings are the only goal, a standard on-grid system may be more straightforward."]
  ], [["See on-grid solar", "/on-grid-solar"], ["See off-grid solar", "/off-grid-solar"], ["Plan a hybrid system", "/get-quote"]]),
  "solar-maintenance": service("Solar Panel Maintenance Nagpur", "Protect system performance with planned care", "Solar panel cleaning, inspection and solar O&M support for residential and commercial systems in Nagpur.", "Solar systems have few moving parts, but regular observation and timely maintenance still matter.", [
    ["What solar maintenance covers", "Typical care includes safe module cleaning, visual inspection, checking mounting and accessible connections, reviewing inverter status and comparing generation trends. Scope varies by system size and site conditions."],
    ["Cleaning frequency is site-specific", "Dust, bird activity, nearby roads, vegetation, roof angle and rainfall affect soiling. Cleaning should use suitable water and non-abrasive methods, with safe roof access and without walking on modules."],
    ["Monitoring helps find hidden losses", "A system may continue running while producing less than expected. Monitoring data, inverter alerts and year-on-year comparisons can reveal shading changes, string issues, downtime or soiling that deserve investigation."],
    ["When to request service", "Seek qualified help for recurring inverter faults, visible cable damage, loose equipment, water ingress, burning smells or unexplained generation drops. Do not open live electrical equipment without appropriate competence and isolation."]
  ], [["Ask about maintenance", "/contact"], ["Understand rooftop systems", "/rooftop-solar-nagpur"], ["Read solar guides", "/blog"]]),

  "solar-solutions": { title: "Solar Solutions in Nagpur | SolarNow", description: "Compare residential, commercial, industrial, on-grid, off-grid and hybrid solar solutions from SolarNow Enterprises in Nagpur.", h1: "A solar solution for each kind of energy need.", intro: "Choose by property type, connection and backup requirement. A site assessment turns that starting point into a real design.", eyebrow: "Solar solutions", sections: [
    { heading: "Solutions by property", paragraphs: ["Homes, commercial buildings and industrial facilities use electricity differently. System size and configuration should reflect those differences."], bullets: ["Residential solar for household energy use", "Commercial solar for daytime business loads", "Industrial solar for larger roofs and facility demand"] },
    { heading: "Solutions by connection", paragraphs: ["An on-grid system prioritises savings with a grid connection. Off-grid solar uses storage to operate independently. Hybrid systems combine solar, grid and batteries for selected backup needs."] },
    { heading: "Services beyond installation", paragraphs: ["SolarNow also supports system assessment, maintenance planning, solar calculator guidance, financing information and carefully maintained subsidy information."] }
  ], related: [["Rooftop solar", "/rooftop-solar-nagpur"], ["Calculate a starting size", "/solar-calculator"], ["Get a quote", "/get-quote"]] },
  "solar-projects": { title: "Solar Projects Nagpur | SolarNow Enterprises", description: "See how SolarNow evaluates rooftop solar projects in Nagpur. Project details are published only when verified and approved.", h1: "Solar projects start with the site, not a template.", intro: "Our project approach connects energy data, roof conditions, engineering and installation planning into one clear path.", eyebrow: "Solar projects Nagpur", sections: [
    { heading: "What project information should show", paragraphs: ["Useful project documentation explains the customer need, site constraints, design response and system scope. We publish only approved, verifiable project details—never fabricated capacities, savings or customer claims."] },
    { heading: "Residential project pathway", paragraphs: ["Home projects typically begin with electricity bills and a roof review. The proposal can then explain usable space, system configuration, metering considerations and any selected backup requirement."] },
    { heading: "Commercial and industrial pathway", paragraphs: ["Larger facilities may require load data, structural input, interconnection review, safety planning and coordination around operating schedules. Maintenance access and monitoring are considered during design."] },
    { heading: "A growing, evidence-led portfolio", paragraphs: ["Verified project profiles can be added here as installations are approved for publication. Each profile should use accurate images, location detail at an appropriate level and measurements that can be substantiated."] }
  ], related: [["Residential solar", "/residential-solar-nagpur"], ["Commercial solar", "/commercial-solar-nagpur"], ["Start your project", "/get-quote"]] },
  "solar-financing": { title: "Solar Financing Nagpur | SolarNow Enterprises", description: "Understand common solar financing considerations, cash-flow questions and due diligence before selecting finance for a Nagpur solar project.", h1: "Finance the system with the same care used to design it.", intro: "Solar finance changes cash flow, risk and ownership. Compare the complete terms, not only the monthly payment.", eyebrow: "Solar financing", sections: [
    { heading: "Common ways to fund solar", paragraphs: ["Depending on the project and available providers, customers may use their own capital, a secured or unsecured loan, business finance or another structured arrangement. Availability and terms can change."] },
    { heading: "Compare the total cost", paragraphs: ["Review interest rate, processing charges, collateral, repayment period, prepayment conditions, insurance, tax treatment and whether any subsidy is assumed. Ask who owns the equipment and warranties throughout the term."] },
    { heading: "Use realistic generation assumptions", paragraphs: ["Repayment planning should allow for weather variation, degradation, downtime and maintenance. A proposal should state its assumptions and should not promise a fixed bill reduction when future tariffs and consumption can change."] }
  ], related: [["Estimate savings", "/solar-calculator"], ["Read subsidy information", "/solar-subsidy"], ["Discuss your project", "/contact"]] },
  "solar-subsidy": { title: "Solar Subsidy Nagpur | Maharashtra Rooftop Guide", description: "Careful, update-friendly guidance on rooftop solar subsidy considerations for Nagpur and Maharashtra. Confirm eligibility through current official sources.", h1: "Solar subsidy information, without outdated promises.", intro: "Schemes, eligibility, approved equipment and application steps can change. Treat this page as a checklist and verify every decision through current official channels.", eyebrow: "Solar subsidy Nagpur", kind: "policy", sections: [
    { heading: "Start with current official guidance", paragraphs: ["Residential rooftop solar support may be available under central or state-linked programmes, subject to current rules. Eligibility can depend on consumer category, system type, capacity, application timing, vendor or equipment requirements and the approved process."], bullets: ["Check the official scheme portal and distribution-company instructions", "Confirm eligibility before placing an order", "Use only the required application and commissioning process", "Keep bills, approvals and commissioning documents"] },
    { heading: "Subsidy is not the same as instant discount", paragraphs: ["Do not assume a subsidy will be received or deduct it from the purchase price unless the applicable process explicitly permits that treatment. Payment timing and verification requirements can affect cash flow."] },
    { heading: "Questions to confirm before proceeding", paragraphs: ["Ask which consumer categories qualify, the capacity limits, whether net metering is required, what equipment specifications apply, how inspection works and which party is responsible for each submission. Save copies of the current rules used for your decision."] },
    { heading: "Last reviewed: September 2026", paragraphs: ["This page intentionally avoids quoting a fixed subsidy amount because programmes and limits can change. SolarNow Enterprises can help explain the project documentation, but only the relevant authority can confirm eligibility and payment."] }
  ], related: [["Residential solar", "/residential-solar-nagpur"], ["Solar calculator", "/solar-calculator"], ["Ask a project question", "/contact"]] },
  "partner-with-us": { title: "Partner With SolarNow | Nagpur Solar Network", description: "Explore responsible supplier, contractor and referral partnerships with SolarNow Enterprises in Nagpur and Kalmeshwar.", h1: "Build better solar outcomes together.", intro: "We welcome conversations with professionals and organisations whose work can improve safe, transparent solar delivery in the Nagpur region.", eyebrow: "Partner with us", sections: [
    { heading: "Potential partnerships", paragraphs: ["Relevant conversations may include electrical and civil execution, structural services, equipment supply, maintenance support, energy consulting and responsible project referrals."], bullets: ["Share clear company and capability information", "State the geography and project sizes you serve", "Provide verifiable product or service documentation", "Avoid unsupported performance or certification claims"] },
    { heading: "How we assess fit", paragraphs: ["Safety practice, technical competence, responsiveness, transparent commercial terms and reliable documentation matter. A conversation does not imply appointment, exclusivity or an ongoing volume commitment."] }
  ], related: [["About SolarNow", "/about"], ["Our solutions", "/solar-solutions"], ["Start a conversation", "/contact"]] },
  contact: { title: "Contact SolarNow | Solar Installer Nagpur", description: "Contact SolarNow Enterprises in Kalmeshwar for solar installation enquiries across Nagpur and surrounding areas.", h1: "Talk to a local solar team.", intro: "Tell us about the property, electricity use and what you want solar to achieve. We’ll help identify the next useful step.", eyebrow: "Contact SolarNow", sections: [
    { heading: "Visit SolarNow Enterprises", paragraphs: ["In Front of Pratap High School, Katol Nagpur Road, Kalmeshwar, Nagpur, Maharashtra 441501.", "Service area: Nagpur, Kalmeshwar and surrounding areas. The business phone number and Google Maps destination are configurable before public launch."] },
    { heading: "Prepare for a useful first conversation", paragraphs: ["If available, keep a recent electricity bill, property type, approximate roof area, connection type and preferred site-visit timing ready. For backup needs, list the appliances or equipment that must operate during an outage."] }
  ], related: [["Request a quote", "/get-quote"], ["Use the solar calculator", "/solar-calculator"], ["Find the right solution", "/solar-solutions"]] },
  "get-quote": { title: "Get a Solar Quote Nagpur | SolarNow Enterprises", description: "Request a solar site assessment for a home, business or industrial property in Nagpur, Kalmeshwar or a nearby area.", h1: "Start with a site-ready solar enquiry.", intro: "A few accurate details help us make the first conversation more useful. Final capacity and pricing require a site and technical assessment.", eyebrow: "Request a solar quote", sections: [
    { heading: "What to share", paragraphs: ["Tell us whether the property is residential, commercial or industrial; its location; typical electricity bill; available roof information; and whether you want backup. Do not send account passwords, identity documents or payment information through an initial enquiry."] },
    { heading: "What happens next", paragraphs: ["We clarify the goal, review the available information and identify whether a site survey is the right next step. A proposal should follow only after enough site and energy information is available."] }
  ], related: [["Calculate a starting estimate", "/solar-calculator"], ["See rooftop solar", "/rooftop-solar-nagpur"], ["Contact details", "/contact"]] },
  blog: { title: "Solar Guides Nagpur | SolarNow Enterprises", description: "Practical guides about rooftop solar, system sizing, savings, maintenance and solar technology for readers in Nagpur.", h1: "Solar guides for better decisions.", intro: "A scalable library for clear, useful solar information—built without thin articles or keyword filler.", eyebrow: "SolarNow knowledge centre", sections: [
    { heading: "Solar guides", paragraphs: ["How rooftop solar works for homes in Nagpur; how to choose the right system size; and how to understand an electricity bill before going solar."] },
    { heading: "Systems and technology", paragraphs: ["On-grid vs off-grid vs hybrid solar; factors that affect solar panel generation; and the role of inverters, batteries, protection and monitoring."] },
    { heading: "Maintenance and policy", paragraphs: ["Solar panel maintenance basics and carefully reviewed explainers for policies or subsidy processes. Policy articles should include a review date and link readers to official confirmation."] },
    { heading: "Publishing standards", paragraphs: ["Future articles should answer a real customer question, name assumptions, avoid guaranteed savings and be reviewed when technology or policy changes. Categories include Residential Solar, Commercial Solar, Solar Savings, Solar Technology, Solar Maintenance and Solar Policies."] }
  ], related: [["Rooftop solar guide", "/rooftop-solar-nagpur"], ["Maintenance guide", "/solar-maintenance"], ["Subsidy information", "/solar-subsidy"]] },
};

function service(title: string, h1: string, description: string, intro: string, sections: [string,string][], related: [string,string][], faqs?: [string,string][]): SitePage {
  return { title, h1, description, intro, eyebrow: "Solar solutions in Nagpur", kind: "service", sections: sections.map(([heading, paragraph]) => ({ heading, paragraphs: [paragraph] })), related, faq: faqs?.map(([q,a]) => ({ q, a })) };
}

export const allSlugs = [...Object.keys(pages), "solar-calculator"];
